version: '2.2'
services:
  chatfiles:
   build: ./chatfiles
   ports:
      - 5000:5000
   environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY}
   volumes:
      - ./chatfiles:/app
  chatfiles-ui:
    build: ./chatfiles-ui
    ports:
      - 3000:3000
    volumes:
      - ./chatfiles-ui:/app
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - CHAT_FILES_SERVER_HOST=http://chatfiles:5000
      - NEXT_PUBLIC_CHAT_FILES_MAX_SIZE=0
    depends_on:
      - chatfiles